<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FilmSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('films')->insert([

            [
                'title' => 'Bela Vingança',
                'original_title' => 'Promising Young Woman',
                'year' => 2020,
                'duration' => 113,
                'synopsis' => 'Nada na vida de Cassie é o que parece ser. Ela é perversamente inteligente, tentadoramente astuta e ainda vive uma vida dupla secreta à noite. Agora, um encontro inesperado está prestes a dar a Cassie a chance de corrigir os erros do passado.',
                'director' => 'Emerald Fennell',
                'image' => 'seeders/bela_vinganca.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Her',
                'original_title' => 'Her',
                'year' => 2013,
                'duration' => 126,
                'synopsis' => 'Em um futuro próximo, Theodore é um homem solitário que desenvolve uma relação improvável com um sistema operacional dotado de inteligência artificial. À medida que a conexão entre eles se aprofunda, ele passa a questionar os limites entre tecnologia, emoção e o que realmente significa amar.',
                'director' => 'Spike Jonze',
                'image' => 'seeders/her.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Um Lugar Silencioso',
                'original_title' => 'A Quiet Place',
                'year' => 2018,
                'duration' => 90,
                'synopsis' => 'Em um mundo devastado por criaturas misteriosas que caçam através do som, uma família precisa viver em completo silêncio para sobreviver. Cada movimento é calculado e cada ruído pode ser fatal, enquanto lutam para proteger seus filhos em meio a um ambiente de constante tensão.',
                'director' => 'John Krasinski',
                'image' => 'seeders/um_lugar_silencioso.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Star Wars',
                'original_title' => 'Star Wars: Episode IV - A New Hope',
                'year' => 1977,
                'duration' => 121,
                'synopsis' => 'Em uma galáxia muito distante, o jovem Luke Skywalker embarca em uma jornada épica ao lado de aliados improváveis para enfrentar o Império Galáctico. Guiado pela Força e por novos mentores, ele descobre seu destino enquanto a Rebelião luta para restaurar a esperança no universo.',
                'director' => 'George Lucas',
                'image' => 'seeders/star_wars.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Jojo Rabbit',
                'original_title' => 'Jojo Rabbit',
                'year' => 2019,
                'duration' => 108,
                'synopsis' => 'Durante a Segunda Guerra Mundial, um jovem alemão extremamente patriota descobre que sua mãe está escondendo uma garota judia em casa. Com a ajuda de seu amigo imaginário — uma versão caricata de Hitler — ele começa a questionar suas crenças e aprende lições inesperadas sobre humanidade e tolerância.',
                'director' => 'Taika Waititi',
                'image' => 'seeders/jojo_rabbit.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Viúva Negra',
                'original_title' => 'Black Widow',
                'year' => 2021,
                'duration' => 134,
                'synopsis' => 'Natasha Romanoff confronta capítulos obscuros de seu passado quando surge uma conspiração ligada à sua antiga vida como espiã. Forçada a enfrentar velhos inimigos e alianças quebradas, ela precisa revisitar sua história antes de se tornar oficialmente uma Vingadora.',
                'director' => 'Cate Shortland',
                'image' => 'seeders/viuva_negra.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Rick and Morty',
                'original_title' => 'Rick and Morty',
                'year' => 2021,
                'duration' => 134,
                'synopsis' => 'Natasha Romanoff confronta capítulos obscuros de seu passado quando surge uma conspiração ligada à sua antiga vida como espiã. Forçada a enfrentar velhos inimigos e alianças quebradas, ela precisa revisitar sua história antes de se tornar oficialmente uma Vingadora.',
                'director' => 'Cate Shortland',
                'image' => 'seeders/rick.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'upcoming',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Lucca',
                'original_title' => 'Lucca',
                'year' => 2021,
                'duration' => 134,
                'synopsis' => 'Natasha Romanoff confronta capítulos obscuros de seu passado quando surge uma conspiração ligada à sua antiga vida como espiã. Forçada a enfrentar velhos inimigos e alianças quebradas, ela precisa revisitar sua história antes de se tornar oficialmente uma Vingadora.',
                'director' => 'Cate Shortland',
                'image' => 'seeders/lucca.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7i5kiFDunk8',
                'status' => 'upcoming',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Batman: O Cavaleiro das Trevas',
                'original_title' => 'The Dark Knight',
                'year' => 2008,
                'duration' => 152,
                'synopsis' => 'Batman enfrenta o Coringa, um criminoso caótico que mergulha Gotham no caos e força o herói a confrontar seus próprios limites morais.',
                'director' => 'Christopher Nolan',
                'image' => 'seeders/batman.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Confusões Pra Cachorro',
                'original_title' => 'Show Dogs',
                'year' => 2018,
                'duration' => 92,
                'synopsis' => 'Um cão policial precisa se infiltrar em um concurso de beleza canino para impedir um esquema ilegal de tráfico de animais.',
                'director' => 'Raja Gosnell',
                'image' => 'seeders/confusao-pra-cachorro.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=1d0Zf9sXlHk',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Golpe Duplo',
                'original_title' => 'Focus',
                'year' => 2015,
                'duration' => 105,
                'synopsis' => 'Um experiente vigarista se envolve com uma iniciante no mundo dos golpes, mas a relação entre os dois complica seus planos.',
                'director' => 'Glenn Ficarra & John Requa',
                'image' => 'seeders/golpe-duplo.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=MxCRgtdAuBo',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Interestelar',
                'original_title' => 'Interstellar',
                'year' => 2014,
                'duration' => 169,
                'synopsis' => 'Um grupo de exploradores viaja através de um buraco de minhoca no espaço em busca de um novo lar para a humanidade.',
                'director' => 'Christopher Nolan',
                'image' => 'seeders/interestelar.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'One Piece',
                'original_title' => 'One Piece',
                'year' => 2023,
                'duration' => 60,
                'synopsis' => 'Monkey D. Luffy e sua tripulação embarcam em uma jornada épica pelos mares em busca do lendário tesouro One Piece.',
                'director' => 'Matt Owens & Steven Maeda',
                'image' => 'seeders/one-piece.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Ades3pQbeh8',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Vingadores: Ultimato',
                'original_title' => 'Avengers: Endgame',
                'year' => 2019,
                'duration' => 181,
                'synopsis' => 'Após os eventos devastadores causados por Thanos, os Vingadores restantes se unem para reverter o destino do universo.',
                'director' => 'Anthony Russo & Joe Russo',
                'image' => 'seeders/vingadores-ultimato.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'status' => 'released',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
